name: Get Info
on: workflow_dispatch

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Get Commits
        id: get-commits
        uses: mohini123/friendly-octo/action.yml
        with:
          owner: mohini123
          repositories: special-dollop

      - name: Print Data
        run: |
          commit_data="${{ steps.get-commits.outputs.commit_data }}"
          echo "Data: $commit_data"
