name: Fetch Merged PRs
on: workflow_dispatch

jobs:
  get-merged-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Get Merged PRs with Labels
        id: get-merged-prs
        uses: ./pr-merge/
        with:
          labels: documentation,bug,question
